### ISSUE TITLE
cut off elements on Samsung S10e

### ISSUE THREAD

**Issue by smartroad** [nicogig/WLED-App#17]
![Screenshot_20210821-090642](https://user-images.githubusercontent.com/1229033/130315382-1bea5232-8bae-4235-ae79-03434348b161.jpg)

As mentioned on your reddit post, I've attached a screen shot of where a couple of elements sre being cut off 😀

**Comment by nicogig** [comment]
Amazing, thank you for the screenshot! I'll make sure this gets fixed in the next release

**Comment by nicogig** [comment]
Fixed in v2.1. Please have a look at the latest build and let me know if you are still seeing this issue!
